FROM node:23.6.1-alpine3.20 AS installer
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm i

FROM node:23.6.1-alpine3.20 AS builder
WORKDIR /usr/src/app
COPY --from=installer /usr/src/app/node_modules ./node_modules
COPY . .
RUN npm run web:build:development

FROM node:23.6.1-alpine3.20 AS runner
WORKDIR /usr/src/app
COPY --from=builder /usr/src/app/dist/apps/web/.next/standalone .
COPY --from=builder /usr/src/app/dist/apps/web/public apps/web/public
COPY --from=builder /usr/src/app/dist/apps/web/.next/static dist/apps/web/.next/static

EXPOSE 3000

ENTRYPOINT [ "node", "apps/web/server.js" ]
