import perfectionist from "eslint-plugin-perfectionist";

export const perfectionistConfig = [
  {
    plugins: {
      perfectionist,
    },
    rules: {
      "perfectionist/sort-array-includes": [
        "error",
        {
          type: "alphabetical",
          order: "asc",
          fallbackSort: { type: "unsorted" },
          ignoreCase: true,
          specialCharacters: "keep",
          groupKind: "literals-first",
          partitionByNewLine: false,
          newlinesBetween: "ignore",
          useConfigurationIf: {},
          groups: [],
          customGroups: [],
        },
      ],
      "perfectionist/sort-classes": [
        "error",
        {
          type: "alphabetical",
          order: "asc",
          fallbackSort: { type: "unsorted" },
          ignoreCase: true,
          specialCharacters: "keep",
          partitionByComment: false,
          partitionByNewLine: false,
          newlinesBetween: "ignore",
          ignoreCallbackDependenciesPatterns: [],
          groups: [
            "index-signature",
            ["static-property", "static-accessor-property"],
            ["static-get-method", "static-set-method"],
            ["protected-static-property", "protected-static-accessor-property"],
            ["protected-static-get-method", "protected-static-set-method"],
            ["private-static-property", "private-static-accessor-property"],
            ["private-static-get-method", "private-static-set-method"],
            "static-block",
            ["property", "accessor-property"],
            ["get-method", "set-method"],
            ["protected-property", "protected-accessor-property"],
            ["protected-get-method", "protected-set-method"],
            ["private-property", "private-accessor-property"],
            ["private-get-method", "private-set-method"],
            "constructor",
            ["static-method", "static-function-property"],
            ["protected-static-method", "protected-static-function-property"],
            ["private-static-method", "private-static-function-property"],
            ["method", "function-property"],
            ["protected-method", "protected-function-property"],
            ["private-method", "private-function-property"],
            "unknown",
          ],
          customGroups: [],
        },
      ],
      "perfectionist/sort-decorators": [
        "error",
        {
          type: "alphabetical",
          order: "asc",
          fallbackSort: { type: "unsorted" },
          ignoreCase: true,
          specialCharacters: "keep",
          groups: [],
          customGroups: {},
          sortOnClasses: true,
          sortOnMethods: true,
          sortOnAccessors: true,
          sortOnProperties: true,
          sortOnParameters: true,
        },
      ],
      "perfectionist/sort-enums": [
        "error",
        {
          type: "alphabetical",
          order: "asc",
          fallbackSort: { type: "unsorted" },
          ignoreCase: true,
          specialCharacters: "keep",
          partitionByComment: false,
          partitionByNewLine: false,
          newlinesBetween: "ignore",
          sortByValue: false,
          forceNumericSort: false,
          groups: [],
          customGroups: [],
        },
      ],
      "perfectionist/sort-exports": [
        "error",
        {
          type: "alphabetical",
          order: "asc",
          fallbackSort: { type: "unsorted" },
          ignoreCase: true,
          specialCharacters: "keep",
          partitionByComment: false,
          partitionByNewLine: false,
          groupKind: "mixed",
        },
      ],
      "perfectionist/sort-heritage-clauses": [
        "error",
        {
          type: "alphabetical",
          order: "asc",
          fallbackSort: { type: "unsorted" },
          ignoreCase: true,
          specialCharacters: "keep",
          groups: [],
          customGroups: {},
        },
      ],
      "perfectionist/sort-imports": [
        "error",
        {
          type: "alphabetical",
          order: "asc",
          fallbackSort: { type: "unsorted" },
          ignoreCase: true,
          specialCharacters: "keep",
          internalPattern: ["^~/.+"],
          partitionByComment: false,
          partitionByNewLine: false,
          newlinesBetween: "always",
          maxLineLength: undefined,
          groups: [
            "type",
            ["builtin", "external"],
            "internal-type",
            "internal",
            ["parent-type", "sibling-type", "index-type"],
            ["parent", "sibling", "index"],
            "object",
            "unknown",
          ],
          customGroups: { type: {}, value: {} },
          environment: "node",
        },
      ],
      "perfectionist/sort-interfaces": [
        "error",
        {
          type: "alphabetical",
          order: "asc",
          fallbackSort: { type: "unsorted" },
          ignoreCase: true,
          specialCharacters: "keep",
          ignorePattern: [],
          partitionByComment: false,
          partitionByNewLine: false,
          newlinesBetween: "ignore",
          useConfigurationIf: {},
          groupKind: "mixed",
          groups: [],
          customGroups: [],
        },
      ],
      "perfectionist/sort-intersection-types": [
        "error",
        {
          type: "alphabetical",
          order: "asc",
          fallbackSort: { type: "unsorted" },
          ignoreCase: true,
          specialCharacters: "keep",
          partitionByComment: false,
          partitionByNewLine: false,
          newlinesBetween: "ignore",
          groups: [],
        },
      ],
      "perfectionist/sort-jsx-props": [
        "error",
        {
          type: "alphabetical",
          order: "asc",
          fallbackSort: { type: "unsorted" },
          ignoreCase: true,
          specialCharacters: "keep",
          ignorePattern: [],
          partitionByNewLine: false,
          newlinesBetween: "ignore",
          useConfigurationIf: {},
          groups: [],
          customGroups: {},
        },
      ],
      "perfectionist/sort-maps": [
        "error",
        {
          type: "alphabetical",
          order: "asc",
          fallbackSort: { type: "unsorted" },
          ignoreCase: true,
          specialCharacters: "keep",
          partitionByNewLine: false,
          useConfigurationIf: {},
          groups: [],
          customGroups: [],
        },
      ],
      "perfectionist/sort-modules": [
        "error",
        {
          type: "alphabetical",
          order: "asc",
          fallbackSort: { type: "unsorted" },
          ignoreCase: true,
          specialCharacters: "keep",
          partitionByComment: false,
          partitionByNewLine: false,
          newlinesBetween: "ignore",
          groups: [
            "declare-enum",
            "export-enum",
            "enum",
            ["declare-interface", "declare-type"],
            ["export-interface", "export-type"],
            ["interface", "type"],
            "declare-class",
            "class",
            "export-class",
            "declare-function",
            "export-function",
            "function",
          ],
          customGroups: [],
        },
      ],
      "perfectionist/sort-named-exports": [
        "error",
        {
          type: "alphabetical",
          order: "asc",
          fallbackSort: { type: "unsorted" },
          ignoreAlias: false,
          ignoreCase: true,
          specialCharacters: "keep",
          groupKind: "mixed",
          partitionByNewLine: false,
          partitionByComment: false,
        },
      ],
      "perfectionist/sort-named-imports": [
        "error",
        {
          type: "alphabetical",
          order: "asc",
          fallbackSort: { type: "unsorted" },
          ignoreAlias: false,
          ignoreCase: true,
          specialCharacters: "keep",
          groupKind: "mixed",
          partitionByNewLine: false,
          partitionByComment: false,
        },
      ],
      "perfectionist/sort-objects": [
        "error",
        {
          type: "alphabetical",
          order: "asc",
          fallbackSort: { type: "unsorted" },
          ignoreCase: true,
          specialCharacters: "keep",
          partitionByComment: false,
          partitionByNewLine: false,
          newlinesBetween: "ignore",
          objectDeclarations: true,
          destructuredObjects: true,
          styledComponents: true,
          ignorePattern: [],
          useConfigurationIf: {},
          groups: [],
          customGroups: [],
        },
      ],
      "perfectionist/sort-object-types": [
        "error",
        {
          type: "alphabetical",
          order: "asc",
          fallbackSort: { type: "unsorted" },
          ignoreCase: true,
          specialCharacters: "keep",
          ignorePattern: [],
          partitionByComment: false,
          partitionByNewLine: false,
          newlinesBetween: "ignore",
          useConfigurationIf: {},
          groups: [],
          customGroups: [],
        },
      ],
      "perfectionist/sort-sets": [
        "error",
        {
          type: "alphabetical",
          order: "asc",
          fallbackSort: { type: "unsorted" },
          ignoreCase: true,
          specialCharacters: "keep",
          groupKind: "literals-first",
          partitionByNewLine: false,
          newlinesBetween: "ignore",
          useConfigurationIf: {},
          groups: [],
          customGroups: [],
        },
      ],
      "perfectionist/sort-switch-case": [
        "error",
        {
          type: "alphabetical",
          order: "asc",
          fallbackSort: { type: "unsorted" },
          ignoreCase: true,
          specialCharacters: "keep",
        },
      ],
      "perfectionist/sort-union-types": [
        "error",
        {
          type: "alphabetical",
          order: "asc",
          fallbackSort: { type: "unsorted" },
          ignoreCase: true,
          specialCharacters: "keep",
          partitionByComment: false,
          partitionByNewLine: false,
          newlinesBetween: "ignore",
          groups: [],
        },
      ],
      "perfectionist/sort-variable-declarations": [
        "error",
        {
          type: "alphabetical",
          order: "asc",
          fallbackSort: { type: "unsorted" },
          ignoreCase: true,
          specialCharacters: "keep",
          partitionByNewLine: false,
          partitionByComment: false,
        },
      ],
    },
  },
];
