import type { Metadata } from 'next';

import { roboto } from '@/src/fonts/roboto.font';
import { MuiUiProvider } from '@/src/providers/mui-ui.provider';
import { NotistackProvider } from '@/src/providers/notistack.provider';
import { ReactNode } from 'react';

export const metadata: Metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={roboto.className}>
          <MuiUiProvider>
            <NotistackProvider>{children}</NotistackProvider>
          </MuiUiProvider>
      </body>
    </html>
  );
}
