import type { Metadata } from 'next';

import { roboto } from '@/src/fonts/roboto.font';
import { MuiUiProvider } from '@/src/providers/mui-ui.provider';
import { NotistackProvider } from '@/src/providers/notistack.provider';
import { TanstackProvider } from '@/src/providers/tanstack-query.provider';
import CssBaseline from '@mui/material/CssBaseline';
import { ReactNode } from 'react';

export const metadata: Metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={roboto.className}>
        <MuiUiProvider>
          <TanstackProvider>
            <NotistackProvider>
              {children}
              <CssBaseline />
            </NotistackProvider>
          </TanstackProvider>
        </MuiUiProvider>
      </body>
    </html>
  );
}
