name: Send Telegram Message

on: [push]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram Message
        uses: cbrgm/telegram-github-action@v1
        with:
          token: ${{ secrets.TELEGRAM_TOKEN }}
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          message: |
            **New commit:** ${{ github.actor }}
            **Commit:** ${{ github.event.head_commit.message }}
            **Repository:** ${{ github.repository }}
            **View changes:** [click](https://github.com/${{ github.repository }}/commit/${{ github.sha }})
