name: Send Telegram Message

on:
  push:
    branches: [polinom]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram Message
        uses: cbrgm/telegram-github-action@v1
        with:
          token: ${{ secrets.TELEGRAM_TOKEN }}
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          message: |
            ⚡️ *Merged to polinom* ⚡️
            *Author:* ${{ github.event.head_commit.author.name }}
            *Email:* ${{ github.event.head_commit.author.email }}
            *Repository:* ${{ github.repository }}
            *Branch:* ${{ github.ref }}
            *Commit:* ${{ github.event.head_commit.message }}
            *Committed At:* ${{ github.event.head_commit.timestamp }}
            *Commit URL:* [View Commit](https://github.com/${{ github.repository }}/commit/${{ github.sha }})
